export type Product = {
  slug: string;
  name: string;
  price: number;
  salePrice?: number;
  saleTag?: string;
  images: string[];
  category: "men" | "women" | "accessories" | "unisex";
  collection?: string;
  sizes: string[];
  colors: { name: string; hex: string }[];
  description: string;
  specs: string[];
  care: string[];
  bestSeller?: boolean;
  newArrival?: boolean;
  earlyAccess?: boolean;
  sourceUrl: string;
};

const img = (id: string, ext = "jpeg") =>
  `https://static.wixstatic.com/media/${id}~mv2.${ext}/v1/fill/w_1000,h_1333,al_c,q_90,enc_auto/${id}~mv2.${ext}`;

const CORE_SIZES = ["XS", "S", "M", "L", "XL", "XXL"];
const BOTTOM_SIZES = ["XS", "S", "M", "L", "XL"];
const BLACK = { name: "Vintage Black", hex: "#1a1a1a" };
const WHITE = { name: "White", hex: "#f5f5f5" };
const NAVY = { name: "Navy", hex: "#111827" };
const HEATHER = { name: "Heather Grey", hex: "#8a8a8a" };

export const PRODUCTS: Product[] = [
  {
    slug: "maxout-core-leggings",
    name: "MAXOUT Core Leggings",
    price: 30,
    images: [img("8255de_1724a3f47d5349b4833349cf453dd53b"), img("8255de_271c306c8b2e4d559f961d6f14008c1a")],
    category: "women",
    collection: "Core",
    sizes: BOTTOM_SIZES,
    colors: [BLACK],
    description: "Everyday training legging with a high-rise waistband and squat-proof compression. Built for lifting, running, and everything in between.",
    specs: ["High-rise waistband", "Four-way stretch", "Moisture-wicking", "Hidden waistband pocket"],
    care: ["Machine wash cold", "Hang to dry", "Do not iron"],
    bestSeller: true,
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-core-leggings",
  },
  {
    slug: "maxout-america-sports-bra",
    name: "MAXOUT America Sports Bra",
    price: 30,
    images: [img("8255de_9084b2d7dcdc4fde8702627accbe1dfd"), img("8255de_2dbb2dd75643407e98e143d39c78314d", "png")],
    category: "women",
    collection: "MAXOUT America",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [BLACK, WHITE],
    description: "Medium-support sports bra with a wide underband and racerback silhouette. Part of the MAXOUT America drop.",
    specs: ["Medium support", "Racerback", "Removable pads", "Moisture-wicking"],
    care: ["Machine wash cold", "Do not tumble dry"],
    newArrival: true,
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-america-sports-bra",
  },
  {
    slug: "maxout-america-crop-top",
    name: "MAXOUT America Crop Top",
    price: 25,
    images: [img("8255de_11006063062d4242abc6142252344851"), img("8255de_6306ec014a584159b54a9214ebe16af3", "png")],
    category: "women",
    collection: "MAXOUT America",
    sizes: ["XS", "S", "M", "L"],
    colors: [BLACK, WHITE],
    description: "Soft cropped tee for training and off-days. Slim through the body with a raw hem.",
    specs: ["Slim crop fit", "Ringspun cotton", "Raw hem"],
    care: ["Machine wash cold", "Tumble dry low"],
    newArrival: true,
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-america-crop-top",
  },
  {
    slug: "maxout-america-tee",
    name: "MAXOUT America Tee",
    price: 30,
    images: [img("8255de_503a3a89ad9d4f31aa618a55f73c1d33"), img("8255de_93112aa636534b27a0b2838bb7c1feda", "png")],
    category: "unisex",
    collection: "MAXOUT America",
    sizes: CORE_SIZES,
    colors: [BLACK, WHITE],
    description: "Heavyweight cotton tee with a boxy fit. Built to be worn hard and washed often.",
    specs: ["240 GSM cotton", "Boxy fit", "Ribbed collar"],
    care: ["Machine wash cold", "Tumble dry low"],
    bestSeller: true,
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-america-tee",
  },
  {
    slug: "maxout-america-sweatpants",
    name: "MAXOUT America Sweatpants",
    price: 45,
    images: [img("8255de_ee621bfc9cc64e3f9a9b47bfdef2b2d3"), img("8255de_141667c3cfff488c831d0022687eb5bf", "png")],
    category: "unisex",
    collection: "MAXOUT America",
    sizes: BOTTOM_SIZES,
    colors: [BLACK],
    description: "Heavyweight fleece sweatpants with a tapered leg and elastic cuffs. Made to move.",
    specs: ["400 GSM brushed fleece", "Tapered leg", "Elastic cuffs", "Side pockets"],
    care: ["Machine wash cold", "Tumble dry low"],
    newArrival: true,
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-america-sweatpants",
  },
  {
    slug: "maxout-core-racerback-tank",
    name: "MAXOUT Core Racerback Tank",
    price: 24,
    images: [img("8255de_fbebc62f5eb74ca1b29e8398d28e576f", "png"), img("8255de_c3aa491925144e41b402cb447d321f49", "png")],
    category: "women",
    collection: "Core",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [BLACK, WHITE],
    description: "Lightweight racerback for training and layering. Soft, breathable, and built to move.",
    specs: ["Lightweight blend", "Racerback silhouette", "Curved hem"],
    care: ["Machine wash cold", "Hang to dry"],
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-core-racerback-tank",
  },
  {
    slug: "maxout-summer-shorts",
    name: "MAXOUT Summer Shorts",
    price: 25,
    salePrice: 20,
    saleTag: "SUMMER SALE",
    images: [img("8255de_f95ef2e05dea449b9ab67eed582b25c7", "png"), img("8255de_9c9cecc5f8c64ad3b1902d0d0b8e45dd", "png")],
    category: "men",
    collection: "Summer",
    sizes: BOTTOM_SIZES,
    colors: [BLACK, HEATHER],
    description: "Lightweight training shorts with an elastic waist and drawcord. Built for hot-weather work.",
    specs: ["6\" inseam", "Elastic waist with drawcord", "Side pockets", "Moisture-wicking"],
    care: ["Machine wash cold", "Tumble dry low"],
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-summer-shorts",
  },
  {
    slug: "maxout-summer-tank",
    name: "MAXOUT Summer Tank",
    price: 28,
    salePrice: 22.4,
    saleTag: "SUMMER SALE",
    images: [img("8255de_90b77a94036c4207ab5d14c42b5ce45f", "png"), img("8255de_bcfebfefa93a4cabb6d64e8722c85f3e", "png")],
    category: "men",
    collection: "Summer",
    sizes: CORE_SIZES,
    colors: [BLACK, WHITE],
    description: "Cut-away training tank in a soft cotton blend. Wear it heavy.",
    specs: ["Deep armhole", "Cotton blend", "Curved hem"],
    care: ["Machine wash cold", "Tumble dry low"],
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-summer-tank",
  },
  {
    slug: "maxout-summer-tee",
    name: "MAXOUT Summer Tee",
    price: 29,
    salePrice: 23.2,
    saleTag: "SUMMER SALE",
    images: [img("8255de_a0985b7bb768415ca1aada43cbdc3470", "png"), img("8255de_f882e70e3dfd412dabf601cc664d3df3", "png")],
    category: "men",
    collection: "Summer",
    sizes: CORE_SIZES,
    colors: [BLACK, WHITE],
    description: "Everyday summer tee in a soft, breathable cotton. Cut for a relaxed fit.",
    specs: ["Relaxed fit", "Ringspun cotton", "Ribbed collar"],
    care: ["Machine wash cold", "Tumble dry low"],
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-summer-tee",
  },
  {
    slug: "maxout-apex-tee",
    name: "MAXOUT Apex Tee",
    price: 35,
    images: [img("8255de_9537a6ec150f420d832d455970f35a95", "png"), img("8255de_b8435c203f3346498893d3401c02d872", "png")],
    category: "men",
    collection: "Apex",
    sizes: CORE_SIZES,
    colors: [BLACK, NAVY],
    description: "Premium training tee with a technical hand-feel. Built for hard sessions and everyday wear.",
    specs: ["Technical cotton blend", "Athletic fit", "Anti-odor finish"],
    care: ["Machine wash cold", "Tumble dry low"],
    bestSeller: true,
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-apex-tee",
  },
  {
    slug: "maxout-core-sports-bra",
    name: "MAXOUT Core Sports Bra",
    price: 27.96,
    images: [img("8255de_e3111cd90e71449b940fb0f17a37eb7a", "png"), img("8255de_b41c98fd18b04729bbe8fe842274caa6", "png")],
    category: "women",
    collection: "Core",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [BLACK, WHITE],
    description: "Everyday sports bra with medium support and a wide underband.",
    specs: ["Medium support", "Removable pads", "Wide underband"],
    care: ["Machine wash cold", "Hang to dry"],
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-core-sports-bra",
  },
  {
    slug: "maxout-core-hoodie-1",
    name: "MAXOUT Core Hoodie",
    price: 55,
    images: [img("8255de_dcba6ed6532b4e198c7c34c77c6a3f7c", "png"), img("8255de_7fe9660c40034b8893a1dd92e1faedf1", "png")],
    category: "unisex",
    collection: "Core",
    sizes: CORE_SIZES,
    colors: [BLACK, HEATHER],
    description: "Everyday hoodie with a heavyweight fleece body and a relaxed fit.",
    specs: ["Heavyweight fleece", "Relaxed fit", "Kangaroo pocket"],
    care: ["Machine wash cold", "Tumble dry low"],
    bestSeller: true,
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-core-hoodie-1",
  },
  {
    slug: "maxout-core-compression-shirt",
    name: "MAXOUT Core Compression Shirt",
    price: 28.5,
    images: [img("8255de_73127059725c4cefb6c4897ce14078b3", "png"), img("8255de_44c6f2b1aa8e41c290683a44d58abd42", "png")],
    category: "men",
    collection: "Core",
    sizes: CORE_SIZES,
    colors: [BLACK, WHITE],
    description: "Second-skin compression fit built for the gym and layering.",
    specs: ["Compression fit", "Four-way stretch", "Flatlock seams"],
    care: ["Machine wash cold", "Hang to dry"],
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-core-compression-shirt",
  },
  {
    slug: "maxout-core-long-sleeve",
    name: "MAXOUT Core Long Sleeve",
    price: 29.5,
    images: [
      "https://static.wixstatic.com/media/8255de_b67e7d362556494d94aa761c9832a8ac~mv2.jpg/v1/fill/w_1000,h_1333,al_c,q_90,enc_auto/ls.jpg",
      "https://static.wixstatic.com/media/8255de_861c0330324342a2a3e4ba418a3492dd~mv2.jpg/v1/fill/w_1000,h_1333,al_c,q_90,enc_auto/ls2.jpg",
    ],
    category: "unisex",
    collection: "Core",
    sizes: CORE_SIZES,
    colors: [BLACK, WHITE],
    description: "Essential long-sleeve tee for training and layering.",
    specs: ["Midweight cotton blend", "Regular fit", "Ribbed cuffs"],
    care: ["Machine wash cold", "Tumble dry low"],
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-core-long-sleeve",
  },
  {
    slug: "maxout-apex-hoodie",
    name: "MAXOUT Apex Hoodie",
    price: 57.94,
    images: [img("8255de_3a36c631a3294515936d7faadb3ffd89", "png"), img("8255de_63bc8a2539b047f1b16bff9854f7b948", "png")],
    category: "unisex",
    collection: "Apex",
    sizes: CORE_SIZES,
    colors: [BLACK, NAVY],
    description: "Premium hoodie with a technical fleece and a clean silhouette.",
    specs: ["Technical fleece", "Regular fit", "Lined hood"],
    care: ["Machine wash cold", "Tumble dry low"],
    earlyAccess: true,
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-apex-hoodie",
  },
  {
    slug: "maxout-core-joggers",
    name: "MAXOUT Core Joggers",
    price: 33,
    images: [img("8255de_4c1a06b0ed1746d29191b905d862e95b", "png"), img("8255de_05c3e3b1b9ce4202a7b6013d925b69b6", "png")],
    category: "men",
    collection: "Core",
    sizes: BOTTOM_SIZES,
    colors: [BLACK, HEATHER],
    description: "Tapered training joggers with a soft brushed interior.",
    specs: ["Tapered fit", "Elastic cuffs", "Side pockets"],
    care: ["Machine wash cold", "Tumble dry low"],
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-core-joggers",
  },
  {
    slug: "maxout-core-tee",
    name: "MAXOUT Core Tee",
    price: 40,
    salePrice: 35,
    images: [img("8255de_f3f706cc329b4988848297d52949225d", "png"), img("8255de_abc9f32c92264002a780b92547cd04bb", "png")],
    category: "unisex",
    collection: "Core",
    sizes: CORE_SIZES,
    colors: [BLACK, WHITE],
    description: "The essential MAXOUT tee. Heavyweight cotton, boxy cut, built to last.",
    specs: ["Heavyweight cotton", "Boxy fit", "Ribbed collar"],
    care: ["Machine wash cold", "Tumble dry low"],
    bestSeller: true,
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-core-tee",
  },
  {
    slug: "unisex-jersey-muscle-tank",
    name: "MAXOUT Core Muscle Tank",
    price: 27.33,
    images: [img("8255de_2f3e53ff77ac4287b77e5f48638aa639"), img("8255de_d534cc25b4054bfb9df6b89dd1abbb83")],
    category: "unisex",
    collection: "Core",
    sizes: CORE_SIZES,
    colors: [BLACK, WHITE, HEATHER],
    description: "Classic muscle tank with a deep armhole. Built for hard sessions.",
    specs: ["Cotton jersey", "Deep armhole", "Regular fit"],
    care: ["Machine wash cold", "Tumble dry low"],
    sourceUrl: "https://www.maxoutshop.com/product-page/unisex-jersey-muscle-tank",
  },
  {
    slug: "maxout-core-shaker",
    name: "MAXOUT Core Shaker",
    price: 24,
    images: [img("8255de_05813bc271ce40d2836f407551f0b63f"), img("8255de_06aa581e0a0c42a0814dd559363e27cf")],
    category: "accessories",
    collection: "Core",
    sizes: ["One Size"],
    colors: [BLACK],
    description: "24 oz shaker with a stainless whisk ball. Built for daily gym use.",
    specs: ["24 oz capacity", "BPA-free", "Leakproof lid", "Stainless whisk ball"],
    care: ["Top-rack dishwasher safe"],
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-core-shaker",
  },
  {
    slug: "maxout-core-pants",
    name: "MAXOUT Core Pants",
    price: 40.59,
    images: [
      "https://static.wixstatic.com/media/8255de_3d2b52e99817409cad4a0ccdd1d7fbd6~mv2.jpg/v1/fill/w_1000,h_1333,al_c,q_90,enc_auto/pants.jpg",
    ],
    category: "men",
    collection: "Core",
    sizes: BOTTOM_SIZES,
    colors: [BLACK],
    description: "Everyday training pant with a clean silhouette and technical comfort.",
    specs: ["Technical blend", "Regular fit", "Zipper pockets"],
    care: ["Machine wash cold", "Tumble dry low"],
    sourceUrl: "https://www.maxoutshop.com/product-page/maxout-core-pants",
  },
];

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function related(slug: string, n = 4) {
  const p = getProduct(slug);
  if (!p) return [];
  return PRODUCTS.filter((x) => x.slug !== slug && (x.collection === p.collection || x.category === p.category)).slice(0, n);
}
