/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as EliteRouteImport } from './routes/elite'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as MessagesHandleRouteImport } from './routes/messages.$handle'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicPushPendingRouteImport } from './routes/api/public/push/pending'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicMobileParseFoodRouteImport } from './routes/api/public/mobile/parse-food'
import { Route as ApiPublicMobileCoachRouteImport } from './routes/api/public/mobile/coach'
import { Route as ApiPublicMobileCheckoutRouteImport } from './routes/api/public/mobile/checkout'
import { Route as ApiPublicMobileCatalogRouteImport } from './routes/api/public/mobile/catalog'
import { Route as ApiPublicHooksNutritionRemindersRouteImport } from './routes/api/public/hooks/nutrition-reminders'
import { Route as ApiPublicMobileEliteStatusRouteImport } from './routes/api/public/mobile/elite/status'
import { Route as ApiPublicMobileElitePortalRouteImport } from './routes/api/public/mobile/elite/portal'
import { Route as ApiPublicMobileEliteCheckoutRouteImport } from './routes/api/public/mobile/elite/checkout'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteRoute = EliteRouteImport.update({
  id: '/elite',
  path: '/elite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesHandleRoute = MessagesHandleRouteImport.update({
  id: '/messages/$handle',
  path: '/messages/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushPendingRoute = ApiPublicPushPendingRouteImport.update({
  id: '/api/public/push/pending',
  path: '/api/public/push/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMobileParseFoodRoute =
  ApiPublicMobileParseFoodRouteImport.update({
    id: '/api/public/mobile/parse-food',
    path: '/api/public/mobile/parse-food',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMobileCoachRoute = ApiPublicMobileCoachRouteImport.update({
  id: '/api/public/mobile/coach',
  path: '/api/public/mobile/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMobileCheckoutRoute = ApiPublicMobileCheckoutRouteImport.update({
  id: '/api/public/mobile/checkout',
  path: '/api/public/mobile/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMobileCatalogRoute = ApiPublicMobileCatalogRouteImport.update({
  id: '/api/public/mobile/catalog',
  path: '/api/public/mobile/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNutritionRemindersRoute =
  ApiPublicHooksNutritionRemindersRouteImport.update({
    id: '/api/public/hooks/nutrition-reminders',
    path: '/api/public/hooks/nutrition-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMobileEliteStatusRoute =
  ApiPublicMobileEliteStatusRouteImport.update({
    id: '/api/public/mobile/elite/status',
    path: '/api/public/mobile/elite/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMobileElitePortalRoute =
  ApiPublicMobileElitePortalRouteImport.update({
    id: '/api/public/mobile/elite/portal',
    path: '/api/public/mobile/elite/portal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMobileEliteCheckoutRoute =
  ApiPublicMobileEliteCheckoutRouteImport.update({
    id: '/api/public/mobile/elite/checkout',
    path: '/api/public/mobile/elite/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/elite': typeof EliteRoute
  '/mcp': typeof McpRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/messages/$handle': typeof MessagesHandleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/messages/': typeof MessagesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/nutrition-reminders': typeof ApiPublicHooksNutritionRemindersRoute
  '/api/public/mobile/catalog': typeof ApiPublicMobileCatalogRoute
  '/api/public/mobile/checkout': typeof ApiPublicMobileCheckoutRoute
  '/api/public/mobile/coach': typeof ApiPublicMobileCoachRoute
  '/api/public/mobile/parse-food': typeof ApiPublicMobileParseFoodRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/push/pending': typeof ApiPublicPushPendingRoute
  '/api/public/mobile/elite/checkout': typeof ApiPublicMobileEliteCheckoutRoute
  '/api/public/mobile/elite/portal': typeof ApiPublicMobileElitePortalRoute
  '/api/public/mobile/elite/status': typeof ApiPublicMobileEliteStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/elite': typeof EliteRoute
  '/mcp': typeof McpRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/messages/$handle': typeof MessagesHandleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/messages': typeof MessagesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/nutrition-reminders': typeof ApiPublicHooksNutritionRemindersRoute
  '/api/public/mobile/catalog': typeof ApiPublicMobileCatalogRoute
  '/api/public/mobile/checkout': typeof ApiPublicMobileCheckoutRoute
  '/api/public/mobile/coach': typeof ApiPublicMobileCoachRoute
  '/api/public/mobile/parse-food': typeof ApiPublicMobileParseFoodRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/push/pending': typeof ApiPublicPushPendingRoute
  '/api/public/mobile/elite/checkout': typeof ApiPublicMobileEliteCheckoutRoute
  '/api/public/mobile/elite/portal': typeof ApiPublicMobileElitePortalRoute
  '/api/public/mobile/elite/status': typeof ApiPublicMobileEliteStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/elite': typeof EliteRoute
  '/mcp': typeof McpRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/messages/$handle': typeof MessagesHandleRoute
  '/product/$slug': typeof ProductSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/messages/': typeof MessagesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/nutrition-reminders': typeof ApiPublicHooksNutritionRemindersRoute
  '/api/public/mobile/catalog': typeof ApiPublicMobileCatalogRoute
  '/api/public/mobile/checkout': typeof ApiPublicMobileCheckoutRoute
  '/api/public/mobile/coach': typeof ApiPublicMobileCoachRoute
  '/api/public/mobile/parse-food': typeof ApiPublicMobileParseFoodRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/push/pending': typeof ApiPublicPushPendingRoute
  '/api/public/mobile/elite/checkout': typeof ApiPublicMobileEliteCheckoutRoute
  '/api/public/mobile/elite/portal': typeof ApiPublicMobileElitePortalRoute
  '/api/public/mobile/elite/status': typeof ApiPublicMobileEliteStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/coach'
    | '/community'
    | '/elite'
    | '/mcp'
    | '/orders'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/rewards'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/checkout/return'
    | '/messages/$handle'
    | '/product/$slug'
    | '/u/$handle'
    | '/messages/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/'
    | '/api/public/hooks/nutrition-reminders'
    | '/api/public/mobile/catalog'
    | '/api/public/mobile/checkout'
    | '/api/public/mobile/coach'
    | '/api/public/mobile/parse-food'
    | '/api/public/payments/webhook'
    | '/api/public/push/pending'
    | '/api/public/mobile/elite/checkout'
    | '/api/public/mobile/elite/portal'
    | '/api/public/mobile/elite/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/coach'
    | '/community'
    | '/elite'
    | '/mcp'
    | '/orders'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/rewards'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/checkout/return'
    | '/messages/$handle'
    | '/product/$slug'
    | '/u/$handle'
    | '/messages'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin'
    | '/api/public/hooks/nutrition-reminders'
    | '/api/public/mobile/catalog'
    | '/api/public/mobile/checkout'
    | '/api/public/mobile/coach'
    | '/api/public/mobile/parse-food'
    | '/api/public/payments/webhook'
    | '/api/public/push/pending'
    | '/api/public/mobile/elite/checkout'
    | '/api/public/mobile/elite/portal'
    | '/api/public/mobile/elite/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/coach'
    | '/community'
    | '/elite'
    | '/mcp'
    | '/orders'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/rewards'
    | '/shop'
    | '/sitemap.xml'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/checkout/return'
    | '/messages/$handle'
    | '/product/$slug'
    | '/u/$handle'
    | '/messages/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/'
    | '/api/public/hooks/nutrition-reminders'
    | '/api/public/mobile/catalog'
    | '/api/public/mobile/checkout'
    | '/api/public/mobile/coach'
    | '/api/public/mobile/parse-food'
    | '/api/public/payments/webhook'
    | '/api/public/push/pending'
    | '/api/public/mobile/elite/checkout'
    | '/api/public/mobile/elite/portal'
    | '/api/public/mobile/elite/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CoachRoute: typeof CoachRoute
  CommunityRoute: typeof CommunityRoute
  EliteRoute: typeof EliteRoute
  McpRoute: typeof McpRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRoute: typeof TrackRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  MessagesHandleRoute: typeof MessagesHandleRoute
  ProductSlugRoute: typeof ProductSlugRoute
  UHandleRoute: typeof UHandleRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksNutritionRemindersRoute: typeof ApiPublicHooksNutritionRemindersRoute
  ApiPublicMobileCatalogRoute: typeof ApiPublicMobileCatalogRoute
  ApiPublicMobileCheckoutRoute: typeof ApiPublicMobileCheckoutRoute
  ApiPublicMobileCoachRoute: typeof ApiPublicMobileCoachRoute
  ApiPublicMobileParseFoodRoute: typeof ApiPublicMobileParseFoodRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPushPendingRoute: typeof ApiPublicPushPendingRoute
  ApiPublicMobileEliteCheckoutRoute: typeof ApiPublicMobileEliteCheckoutRoute
  ApiPublicMobileElitePortalRoute: typeof ApiPublicMobileElitePortalRoute
  ApiPublicMobileEliteStatusRoute: typeof ApiPublicMobileEliteStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite': {
      id: '/elite'
      path: '/elite'
      fullPath: '/elite'
      preLoaderRoute: typeof EliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$handle': {
      id: '/messages/$handle'
      path: '/messages/$handle'
      fullPath: '/messages/$handle'
      preLoaderRoute: typeof MessagesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/pending': {
      id: '/api/public/push/pending'
      path: '/api/public/push/pending'
      fullPath: '/api/public/push/pending'
      preLoaderRoute: typeof ApiPublicPushPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/parse-food': {
      id: '/api/public/mobile/parse-food'
      path: '/api/public/mobile/parse-food'
      fullPath: '/api/public/mobile/parse-food'
      preLoaderRoute: typeof ApiPublicMobileParseFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/coach': {
      id: '/api/public/mobile/coach'
      path: '/api/public/mobile/coach'
      fullPath: '/api/public/mobile/coach'
      preLoaderRoute: typeof ApiPublicMobileCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/checkout': {
      id: '/api/public/mobile/checkout'
      path: '/api/public/mobile/checkout'
      fullPath: '/api/public/mobile/checkout'
      preLoaderRoute: typeof ApiPublicMobileCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/catalog': {
      id: '/api/public/mobile/catalog'
      path: '/api/public/mobile/catalog'
      fullPath: '/api/public/mobile/catalog'
      preLoaderRoute: typeof ApiPublicMobileCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nutrition-reminders': {
      id: '/api/public/hooks/nutrition-reminders'
      path: '/api/public/hooks/nutrition-reminders'
      fullPath: '/api/public/hooks/nutrition-reminders'
      preLoaderRoute: typeof ApiPublicHooksNutritionRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/elite/status': {
      id: '/api/public/mobile/elite/status'
      path: '/api/public/mobile/elite/status'
      fullPath: '/api/public/mobile/elite/status'
      preLoaderRoute: typeof ApiPublicMobileEliteStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/elite/portal': {
      id: '/api/public/mobile/elite/portal'
      path: '/api/public/mobile/elite/portal'
      fullPath: '/api/public/mobile/elite/portal'
      preLoaderRoute: typeof ApiPublicMobileElitePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mobile/elite/checkout': {
      id: '/api/public/mobile/elite/checkout'
      path: '/api/public/mobile/elite/checkout'
      fullPath: '/api/public/mobile/elite/checkout'
      preLoaderRoute: typeof ApiPublicMobileEliteCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CoachRoute: CoachRoute,
  CommunityRoute: CommunityRoute,
  EliteRoute: EliteRoute,
  McpRoute: McpRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRoute: TrackRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  MessagesHandleRoute: MessagesHandleRoute,
  ProductSlugRoute: ProductSlugRoute,
  UHandleRoute: UHandleRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksNutritionRemindersRoute: ApiPublicHooksNutritionRemindersRoute,
  ApiPublicMobileCatalogRoute: ApiPublicMobileCatalogRoute,
  ApiPublicMobileCheckoutRoute: ApiPublicMobileCheckoutRoute,
  ApiPublicMobileCoachRoute: ApiPublicMobileCoachRoute,
  ApiPublicMobileParseFoodRoute: ApiPublicMobileParseFoodRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPushPendingRoute: ApiPublicPushPendingRoute,
  ApiPublicMobileEliteCheckoutRoute: ApiPublicMobileEliteCheckoutRoute,
  ApiPublicMobileElitePortalRoute: ApiPublicMobileElitePortalRoute,
  ApiPublicMobileEliteStatusRoute: ApiPublicMobileEliteStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
